### ISSUE TITLE
Where to start

### ISSUE THREAD

**Issue by ghost** [OmegaT-L10N/pt#1]
Hello,

I started to use OmegaT and, obviously, it came to mind translating the program itself, since it seems no one is working on pt (Portugal).
@kosivantsov you seem to be the repo manager, can you direct me to the starting point, please?
I cloned the repo, but...

Many thanks in advance.

**Comment by kosivantsov** [comment]
No need to clone the repo. Check the info here: https://omegat-l10n.github.io
